layers:
  - Input:
      shape: [~, ~, num_bands]
  - EfficientNet:
      input_shape: [~, ~, num_bands]
      name: efficientnet
      width_coefficient: 1.1
      depth_coefficient: 1.2
  - Conv2D:
      filters: 144
      kernel_size: [5, 5]
      padding: same
  - BatchNormalization:
  - Activation:
      activation: relu
  - UpSampling2D:
      size: 2
  - Conv2D:
      filters: 64
      kernel_size: [3, 3]
      padding: same
  - BatchNormalization:
  - Activation:
      activation: relu
  - UpSampling2D:
      size: 2
  - Conv2D:
      filters: 24
      kernel_size: [5, 5]
      padding: same
  - BatchNormalization:
  - Activation:
      activation: relu
  - UpSampling2D:
      size: 2
  - Conv2D:
      filters: 16
      kernel_size: [3, 3]
      padding: same
  - BatchNormalization:
  - Activation:
      activation: relu
  - UpSampling2D:
      size: 2
  - Conv2D:
      filters: 16
      kernel_size: [3, 3]
      padding: same
  - BatchNormalization:
  - Activation:
      activation: relu
  - UpSampling2D:
      size: 2
  - Conv2D:
      filters: num_bands
      kernel_size: [7, 7]
      activation: relu
      padding: same
